
#ifndef _IndepentdentStudyUI_IndepentdentStudyUISettings_h
#define _IndepentdentStudyUI_IndepentdentStudyUISettings_h


/*
 * IndepentdentStudyUISettings.h -- part of the IndepentdentStudyUI project.
 * Hard-coded system settings, configurable through #defines
 * Emma McDonnell
 * Northwestern University https://github.com/ej-mcdonnell
 * 
 * Copyright (C) 2017 Emma McDonnell
 * 
 * Generated by DruidBuilder [https://devicedruid.com/], 
 * as part of project "ba95b28a789c481fb331c26c854e8d00M1JIfoUoZr",
 * aka IndepentdentStudyUI.
 * 
 * Druid4Arduino, Device Druid, Druid Builder, the builder 
 * code brewery and its wizards, SerialUI and supporting 
 * libraries, as well as the generated parts of this program 
 * are 
 *            Copyright (C) 2013-2017 Pat Deegan 
 * [http://psychogenic.com/ | http://flyingcarsandstuff.com/]
 * and distributed under the terms of their respective licenses.
 * See http://devicedruid.com for details.
 * 
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 
 * THE ENTIRE RISK AS TO THE QUALITY AND PERFORMANCE OF THE 
 * PROGRAM IS WITH YOU. SHOULD THE PROGRAM PROVE DEFECTIVE, 
 * YOU ASSUME THE COST OF ALL NECESSARY SERVICING, REPAIR OR
 * CORRECTION.
 * 
 * Keep in mind that there is no warranty and you are solely 
 * responsible for the use of all these cool tools.
 * 
 * Play safe, have fun.
 * 
 */



/* Defaults should be fine, but you may set each to 
 * something appropriate for your situation.
 * 
 * Of special interest: serial_baud_rate -- this must match 
 * what you specify while using the Druid GUI
 */

// serial_baud_rate -- connect to device at this baud rate, using druid
#define serial_baud_rate			57600



// serial_maxidle_ms -- how long before we consider the user
// gone, for lack of activity (milliseconds)
#define serial_maxidle_ms			30000

// serial_readtimeout_ms -- timeout when we're expecting input
// for a specific request/read (milliseconds)
#define serial_readtimeout_ms		20000

#define serial_ui_greeting_str	"+++ IndepentdentStudyUI +++\r\nEnter '?' for options."
// serial_input_terminator -- what we consider an <ENTER> (i.e. newline)
#define serial_input_terminator		'\n'

// if you included requests for "strings", 
// request_inputstring_maxlen will set the max length allowable
// (bigger need more RAM)
#define request_inputstring_maxlen	50



#endif
